<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/05/09 14:17:36

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:root@localhost/GNLF',
  'encode' => 'utf8',
), 'propel');
$this->databases['propel'] = $database;
