<?php
// auto-generated by sfPropelCrud
// date: 2014/05/09 14:14:41
?>
<?php use_helper('Object') ?>

<?php echo form_tag('writein/update') ?>

<?php echo object_input_hidden_tag($writein, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Title:</th>
  <td><?php echo object_textarea_tag($writein, 'getTitle', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Body:</th>
  <td><?php echo object_textarea_tag($writein, 'getBody', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($writein->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'writein/delete?id='.$writein->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'writein/show?id='.$writein->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'writein/list') ?>
<?php endif; ?>
</form>
